import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import NavBar from '@/components/Navbar'
import Providers from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Enfermeria PUCE-SI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/spacelab/bootstrap.min.css' />
      </head>
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
        <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js'></Script>
      </body>
    </html>
  )
}
